// Code generated by mockery v2.53.5. DO NOT EDIT.

package tablemock

import (
	piece "github.com/anthonybrice/editor/internal/buffer/piece"
	mock "github.com/stretchr/testify/mock"
)

// MockTable is an autogenerated mock type for the Table type
type MockTable struct {
	mock.Mock
}

type MockTable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTable) EXPECT() *MockTable_Expecter {
	return &MockTable_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: start, end
func (_m *MockTable) Delete(start int, end int) {
	_m.Called(start, end)
}

// MockTable_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTable_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - start int
//   - end int
func (_e *MockTable_Expecter) Delete(start interface{}, end interface{}) *MockTable_Delete_Call {
	return &MockTable_Delete_Call{Call: _e.mock.On("Delete", start, end)}
}

func (_c *MockTable_Delete_Call) Run(run func(start int, end int)) *MockTable_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTable_Delete_Call) Return() *MockTable_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTable_Delete_Call) RunAndReturn(run func(int, int)) *MockTable_Delete_Call {
	_c.Run(run)
	return _c
}

// Insert provides a mock function with given fields: pos, text
func (_m *MockTable) Insert(pos int, text []rune) {
	_m.Called(pos, text)
}

// MockTable_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTable_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - pos int
//   - text []rune
func (_e *MockTable_Expecter) Insert(pos interface{}, text interface{}) *MockTable_Insert_Call {
	return &MockTable_Insert_Call{Call: _e.mock.On("Insert", pos, text)}
}

func (_c *MockTable_Insert_Call) Run(run func(pos int, text []rune)) *MockTable_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]rune))
	})
	return _c
}

func (_c *MockTable_Insert_Call) Return() *MockTable_Insert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTable_Insert_Call) RunAndReturn(run func(int, []rune)) *MockTable_Insert_Call {
	_c.Run(run)
	return _c
}

// InsertLine provides a mock function with given fields: row, text
func (_m *MockTable) InsertLine(row int, text string) {
	_m.Called(row, text)
}

// MockTable_InsertLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLine'
type MockTable_InsertLine_Call struct {
	*mock.Call
}

// InsertLine is a helper method to define mock.On call
//   - row int
//   - text string
func (_e *MockTable_Expecter) InsertLine(row interface{}, text interface{}) *MockTable_InsertLine_Call {
	return &MockTable_InsertLine_Call{Call: _e.mock.On("InsertLine", row, text)}
}

func (_c *MockTable_InsertLine_Call) Run(run func(row int, text string)) *MockTable_InsertLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(string))
	})
	return _c
}

func (_c *MockTable_InsertLine_Call) Return() *MockTable_InsertLine_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTable_InsertLine_Call) RunAndReturn(run func(int, string)) *MockTable_InsertLine_Call {
	_c.Run(run)
	return _c
}

// Len provides a mock function with no fields
func (_m *MockTable) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTable_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockTable_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockTable_Expecter) Len() *MockTable_Len_Call {
	return &MockTable_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockTable_Len_Call) Run(run func()) *MockTable_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTable_Len_Call) Return(_a0 int) *MockTable_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_Len_Call) RunAndReturn(run func() int) *MockTable_Len_Call {
	_c.Call.Return(run)
	return _c
}

// Line provides a mock function with given fields: row
func (_m *MockTable) Line(row int) string {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for Line")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTable_Line_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Line'
type MockTable_Line_Call struct {
	*mock.Call
}

// Line is a helper method to define mock.On call
//   - row int
func (_e *MockTable_Expecter) Line(row interface{}) *MockTable_Line_Call {
	return &MockTable_Line_Call{Call: _e.mock.On("Line", row)}
}

func (_c *MockTable_Line_Call) Run(run func(row int)) *MockTable_Line_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTable_Line_Call) Return(_a0 string) *MockTable_Line_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_Line_Call) RunAndReturn(run func(int) string) *MockTable_Line_Call {
	_c.Call.Return(run)
	return _c
}

// LineCount provides a mock function with no fields
func (_m *MockTable) LineCount() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LineCount")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTable_LineCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineCount'
type MockTable_LineCount_Call struct {
	*mock.Call
}

// LineCount is a helper method to define mock.On call
func (_e *MockTable_Expecter) LineCount() *MockTable_LineCount_Call {
	return &MockTable_LineCount_Call{Call: _e.mock.On("LineCount")}
}

func (_c *MockTable_LineCount_Call) Run(run func()) *MockTable_LineCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTable_LineCount_Call) Return(_a0 int) *MockTable_LineCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_LineCount_Call) RunAndReturn(run func() int) *MockTable_LineCount_Call {
	_c.Call.Return(run)
	return _c
}

// LineEnd provides a mock function with given fields: row
func (_m *MockTable) LineEnd(row int) int {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for LineEnd")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTable_LineEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineEnd'
type MockTable_LineEnd_Call struct {
	*mock.Call
}

// LineEnd is a helper method to define mock.On call
//   - row int
func (_e *MockTable_Expecter) LineEnd(row interface{}) *MockTable_LineEnd_Call {
	return &MockTable_LineEnd_Call{Call: _e.mock.On("LineEnd", row)}
}

func (_c *MockTable_LineEnd_Call) Run(run func(row int)) *MockTable_LineEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTable_LineEnd_Call) Return(_a0 int) *MockTable_LineEnd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_LineEnd_Call) RunAndReturn(run func(int) int) *MockTable_LineEnd_Call {
	_c.Call.Return(run)
	return _c
}

// LineLen provides a mock function with given fields: row
func (_m *MockTable) LineLen(row int) int {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for LineLen")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTable_LineLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineLen'
type MockTable_LineLen_Call struct {
	*mock.Call
}

// LineLen is a helper method to define mock.On call
//   - row int
func (_e *MockTable_Expecter) LineLen(row interface{}) *MockTable_LineLen_Call {
	return &MockTable_LineLen_Call{Call: _e.mock.On("LineLen", row)}
}

func (_c *MockTable_LineLen_Call) Run(run func(row int)) *MockTable_LineLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTable_LineLen_Call) Return(_a0 int) *MockTable_LineLen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_LineLen_Call) RunAndReturn(run func(int) int) *MockTable_LineLen_Call {
	_c.Call.Return(run)
	return _c
}

// LineRunes provides a mock function with given fields: row
func (_m *MockTable) LineRunes(row int) []rune {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for LineRunes")
	}

	var r0 []rune
	if rf, ok := ret.Get(0).(func(int) []rune); ok {
		r0 = rf(row)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rune)
		}
	}

	return r0
}

// MockTable_LineRunes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineRunes'
type MockTable_LineRunes_Call struct {
	*mock.Call
}

// LineRunes is a helper method to define mock.On call
//   - row int
func (_e *MockTable_Expecter) LineRunes(row interface{}) *MockTable_LineRunes_Call {
	return &MockTable_LineRunes_Call{Call: _e.mock.On("LineRunes", row)}
}

func (_c *MockTable_LineRunes_Call) Run(run func(row int)) *MockTable_LineRunes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTable_LineRunes_Call) Return(_a0 []rune) *MockTable_LineRunes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_LineRunes_Call) RunAndReturn(run func(int) []rune) *MockTable_LineRunes_Call {
	_c.Call.Return(run)
	return _c
}

// LineStart provides a mock function with given fields: row
func (_m *MockTable) LineStart(row int) int {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for LineStart")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTable_LineStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineStart'
type MockTable_LineStart_Call struct {
	*mock.Call
}

// LineStart is a helper method to define mock.On call
//   - row int
func (_e *MockTable_Expecter) LineStart(row interface{}) *MockTable_LineStart_Call {
	return &MockTable_LineStart_Call{Call: _e.mock.On("LineStart", row)}
}

func (_c *MockTable_LineStart_Call) Run(run func(row int)) *MockTable_LineStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTable_LineStart_Call) Return(_a0 int) *MockTable_LineStart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_LineStart_Call) RunAndReturn(run func(int) int) *MockTable_LineStart_Call {
	_c.Call.Return(run)
	return _c
}

// Lines provides a mock function with no fields
func (_m *MockTable) Lines() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lines")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockTable_Lines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lines'
type MockTable_Lines_Call struct {
	*mock.Call
}

// Lines is a helper method to define mock.On call
func (_e *MockTable_Expecter) Lines() *MockTable_Lines_Call {
	return &MockTable_Lines_Call{Call: _e.mock.On("Lines")}
}

func (_c *MockTable_Lines_Call) Run(run func()) *MockTable_Lines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTable_Lines_Call) Return(_a0 []string) *MockTable_Lines_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_Lines_Call) RunAndReturn(run func() []string) *MockTable_Lines_Call {
	_c.Call.Return(run)
	return _c
}

// OffsetToPos provides a mock function with given fields: offset
func (_m *MockTable) OffsetToPos(offset int) (int, int) {
	ret := _m.Called(offset)

	if len(ret) == 0 {
		panic("no return value specified for OffsetToPos")
	}

	var r0 int
	var r1 int
	if rf, ok := ret.Get(0).(func(int) (int, int)); ok {
		return rf(offset)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(offset)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) int); ok {
		r1 = rf(offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// MockTable_OffsetToPos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OffsetToPos'
type MockTable_OffsetToPos_Call struct {
	*mock.Call
}

// OffsetToPos is a helper method to define mock.On call
//   - offset int
func (_e *MockTable_Expecter) OffsetToPos(offset interface{}) *MockTable_OffsetToPos_Call {
	return &MockTable_OffsetToPos_Call{Call: _e.mock.On("OffsetToPos", offset)}
}

func (_c *MockTable_OffsetToPos_Call) Run(run func(offset int)) *MockTable_OffsetToPos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockTable_OffsetToPos_Call) Return(row int, col int) *MockTable_OffsetToPos_Call {
	_c.Call.Return(row, col)
	return _c
}

func (_c *MockTable_OffsetToPos_Call) RunAndReturn(run func(int) (int, int)) *MockTable_OffsetToPos_Call {
	_c.Call.Return(run)
	return _c
}

// PosToOffset provides a mock function with given fields: row, col
func (_m *MockTable) PosToOffset(row int, col int) int {
	ret := _m.Called(row, col)

	if len(ret) == 0 {
		panic("no return value specified for PosToOffset")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(row, col)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockTable_PosToOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PosToOffset'
type MockTable_PosToOffset_Call struct {
	*mock.Call
}

// PosToOffset is a helper method to define mock.On call
//   - row int
//   - col int
func (_e *MockTable_Expecter) PosToOffset(row interface{}, col interface{}) *MockTable_PosToOffset_Call {
	return &MockTable_PosToOffset_Call{Call: _e.mock.On("PosToOffset", row, col)}
}

func (_c *MockTable_PosToOffset_Call) Run(run func(row int, col int)) *MockTable_PosToOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTable_PosToOffset_Call) Return(_a0 int) *MockTable_PosToOffset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_PosToOffset_Call) RunAndReturn(run func(int, int) int) *MockTable_PosToOffset_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: s
func (_m *MockTable) Restore(s piece.Snapshot) {
	_m.Called(s)
}

// MockTable_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockTable_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - s piece.Snapshot
func (_e *MockTable_Expecter) Restore(s interface{}) *MockTable_Restore_Call {
	return &MockTable_Restore_Call{Call: _e.mock.On("Restore", s)}
}

func (_c *MockTable_Restore_Call) Run(run func(s piece.Snapshot)) *MockTable_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(piece.Snapshot))
	})
	return _c
}

func (_c *MockTable_Restore_Call) Return() *MockTable_Restore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTable_Restore_Call) RunAndReturn(run func(piece.Snapshot)) *MockTable_Restore_Call {
	_c.Run(run)
	return _c
}

// Slice provides a mock function with given fields: start, end
func (_m *MockTable) Slice(start int, end int) []rune {
	ret := _m.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for Slice")
	}

	var r0 []rune
	if rf, ok := ret.Get(0).(func(int, int) []rune); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rune)
		}
	}

	return r0
}

// MockTable_Slice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slice'
type MockTable_Slice_Call struct {
	*mock.Call
}

// Slice is a helper method to define mock.On call
//   - start int
//   - end int
func (_e *MockTable_Expecter) Slice(start interface{}, end interface{}) *MockTable_Slice_Call {
	return &MockTable_Slice_Call{Call: _e.mock.On("Slice", start, end)}
}

func (_c *MockTable_Slice_Call) Run(run func(start int, end int)) *MockTable_Slice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockTable_Slice_Call) Return(_a0 []rune) *MockTable_Slice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_Slice_Call) RunAndReturn(run func(int, int) []rune) *MockTable_Slice_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function with no fields
func (_m *MockTable) Snapshot() piece.Snapshot {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 piece.Snapshot
	if rf, ok := ret.Get(0).(func() piece.Snapshot); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(piece.Snapshot)
	}

	return r0
}

// MockTable_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type MockTable_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
func (_e *MockTable_Expecter) Snapshot() *MockTable_Snapshot_Call {
	return &MockTable_Snapshot_Call{Call: _e.mock.On("Snapshot")}
}

func (_c *MockTable_Snapshot_Call) Run(run func()) *MockTable_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTable_Snapshot_Call) Return(_a0 piece.Snapshot) *MockTable_Snapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_Snapshot_Call) RunAndReturn(run func() piece.Snapshot) *MockTable_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockTable) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTable_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockTable_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockTable_Expecter) String() *MockTable_String_Call {
	return &MockTable_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockTable_String_Call) Run(run func()) *MockTable_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTable_String_Call) Return(_a0 string) *MockTable_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTable_String_Call) RunAndReturn(run func() string) *MockTable_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTable creates a new instance of MockTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTable {
	mock := &MockTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
