with-expecter: true
packages:
  github.com/anthonybrice/editor/internal/buffer/gap:
    interfaces:
      Buffer:
  github.com/anthonybrice/editor/internal/buffer/piece:
    interfaces:
      Table:
      UndoStore:
  github.com/anthonybrice/editor/internal/buffer:
    interfaces:
      Buffer:
  github.com/anthonybrice/editor/internal/editor:
    interfaces:
      Editor:
  github.com/anthonybrice/editor/internal/lsp:
    interfaces:
      Session:
