packages:
  github.com/anthonybrice/editor/buffer/gap:
    interfaces:
      Buffer:
        config:
          dir: "{{.InterfaceDir}}/mock"
          pkgname: mock
          filename: mock_Buffer.go
  github.com/anthonybrice/editor/buffer/piece:
    interfaces:
      Table:
        config:
          dir: "{{.InterfaceDir}}/tablemock"
          pkgname: tablemock
          filename: mock_Table.go
      UndoStore:
        config:
          dir: "{{.InterfaceDir}}/mockstore"
          pkgname: mockstore
          filename: mock_UndoStore.go
  github.com/anthonybrice/editor/buffer:
    interfaces:
      Buffer:
        config:
          dir: "{{.InterfaceDir}}/mock"
          pkgname: mock
          filename: mock_Buffer.go
  github.com/anthonybrice/editor/editor:
    interfaces:
      Editor:
        config:
          dir: "{{.InterfaceDir}}/mock"
          pkgname: mock
          filename: mock_Editor.go
  github.com/anthonybrice/editor/lsp:
    interfaces:
      Session:
        config:
          dir: "{{.InterfaceDir}}/mock"
          pkgname: mock
          filename: mock_Session.go
