// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/anthonybrice/editor/lsp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSession creates a new instance of MockSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSession {
	mock := &MockSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSession is an autogenerated mock type for the Session type
type MockSession struct {
	mock.Mock
}

type MockSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSession) EXPECT() *MockSession_Expecter {
	return &MockSession_Expecter{mock: &_m.Mock}
}

// Completion provides a mock function for the type MockSession
func (_mock *MockSession) Completion(ctx context.Context, path string, line int, char int) ([]lsp.CompletionItem, error) {
	ret := _mock.Called(ctx, path, line, char)

	if len(ret) == 0 {
		panic("no return value specified for Completion")
	}

	var r0 []lsp.CompletionItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]lsp.CompletionItem, error)); ok {
		return returnFunc(ctx, path, line, char)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []lsp.CompletionItem); ok {
		r0 = returnFunc(ctx, path, line, char)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lsp.CompletionItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, path, line, char)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Completion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Completion'
type MockSession_Completion_Call struct {
	*mock.Call
}

// Completion is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - line int
//   - char int
func (_e *MockSession_Expecter) Completion(ctx interface{}, path interface{}, line interface{}, char interface{}) *MockSession_Completion_Call {
	return &MockSession_Completion_Call{Call: _e.mock.On("Completion", ctx, path, line, char)}
}

func (_c *MockSession_Completion_Call) Run(run func(ctx context.Context, path string, line int, char int)) *MockSession_Completion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSession_Completion_Call) Return(completionItems []lsp.CompletionItem, err error) *MockSession_Completion_Call {
	_c.Call.Return(completionItems, err)
	return _c
}

func (_c *MockSession_Completion_Call) RunAndReturn(run func(ctx context.Context, path string, line int, char int) ([]lsp.CompletionItem, error)) *MockSession_Completion_Call {
	_c.Call.Return(run)
	return _c
}

// Definition provides a mock function for the type MockSession
func (_mock *MockSession) Definition(ctx context.Context, path string, line int, char int) ([]lsp.Location, error) {
	ret := _mock.Called(ctx, path, line, char)

	if len(ret) == 0 {
		panic("no return value specified for Definition")
	}

	var r0 []lsp.Location
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]lsp.Location, error)); ok {
		return returnFunc(ctx, path, line, char)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []lsp.Location); ok {
		r0 = returnFunc(ctx, path, line, char)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lsp.Location)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, path, line, char)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Definition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Definition'
type MockSession_Definition_Call struct {
	*mock.Call
}

// Definition is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - line int
//   - char int
func (_e *MockSession_Expecter) Definition(ctx interface{}, path interface{}, line interface{}, char interface{}) *MockSession_Definition_Call {
	return &MockSession_Definition_Call{Call: _e.mock.On("Definition", ctx, path, line, char)}
}

func (_c *MockSession_Definition_Call) Run(run func(ctx context.Context, path string, line int, char int)) *MockSession_Definition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSession_Definition_Call) Return(locations []lsp.Location, err error) *MockSession_Definition_Call {
	_c.Call.Return(locations, err)
	return _c
}

func (_c *MockSession_Definition_Call) RunAndReturn(run func(ctx context.Context, path string, line int, char int) ([]lsp.Location, error)) *MockSession_Definition_Call {
	_c.Call.Return(run)
	return _c
}

// DidChange provides a mock function for the type MockSession
func (_mock *MockSession) DidChange(ctx context.Context, path string, text string) error {
	ret := _mock.Called(ctx, path, text)

	if len(ret) == 0 {
		panic("no return value specified for DidChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, path, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_DidChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DidChange'
type MockSession_DidChange_Call struct {
	*mock.Call
}

// DidChange is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - text string
func (_e *MockSession_Expecter) DidChange(ctx interface{}, path interface{}, text interface{}) *MockSession_DidChange_Call {
	return &MockSession_DidChange_Call{Call: _e.mock.On("DidChange", ctx, path, text)}
}

func (_c *MockSession_DidChange_Call) Run(run func(ctx context.Context, path string, text string)) *MockSession_DidChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSession_DidChange_Call) Return(err error) *MockSession_DidChange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_DidChange_Call) RunAndReturn(run func(ctx context.Context, path string, text string) error) *MockSession_DidChange_Call {
	_c.Call.Return(run)
	return _c
}

// DidOpen provides a mock function for the type MockSession
func (_mock *MockSession) DidOpen(ctx context.Context, path string, text string) error {
	ret := _mock.Called(ctx, path, text)

	if len(ret) == 0 {
		panic("no return value specified for DidOpen")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, path, text)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_DidOpen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DidOpen'
type MockSession_DidOpen_Call struct {
	*mock.Call
}

// DidOpen is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - text string
func (_e *MockSession_Expecter) DidOpen(ctx interface{}, path interface{}, text interface{}) *MockSession_DidOpen_Call {
	return &MockSession_DidOpen_Call{Call: _e.mock.On("DidOpen", ctx, path, text)}
}

func (_c *MockSession_DidOpen_Call) Run(run func(ctx context.Context, path string, text string)) *MockSession_DidOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSession_DidOpen_Call) Return(err error) *MockSession_DidOpen_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_DidOpen_Call) RunAndReturn(run func(ctx context.Context, path string, text string) error) *MockSession_DidOpen_Call {
	_c.Call.Return(run)
	return _c
}

// DidSave provides a mock function for the type MockSession
func (_mock *MockSession) DidSave(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DidSave")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_DidSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DidSave'
type MockSession_DidSave_Call struct {
	*mock.Call
}

// DidSave is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockSession_Expecter) DidSave(ctx interface{}, path interface{}) *MockSession_DidSave_Call {
	return &MockSession_DidSave_Call{Call: _e.mock.On("DidSave", ctx, path)}
}

func (_c *MockSession_DidSave_Call) Run(run func(ctx context.Context, path string)) *MockSession_DidSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSession_DidSave_Call) Return(err error) *MockSession_DidSave_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_DidSave_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockSession_DidSave_Call {
	_c.Call.Return(run)
	return _c
}

// Exited provides a mock function for the type MockSession
func (_mock *MockSession) Exited() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Exited")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockSession_Exited_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exited'
type MockSession_Exited_Call struct {
	*mock.Call
}

// Exited is a helper method to define mock.On call
func (_e *MockSession_Expecter) Exited() *MockSession_Exited_Call {
	return &MockSession_Exited_Call{Call: _e.mock.On("Exited")}
}

func (_c *MockSession_Exited_Call) Run(run func()) *MockSession_Exited_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_Exited_Call) Return(valCh <-chan struct{}) *MockSession_Exited_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockSession_Exited_Call) RunAndReturn(run func() <-chan struct{}) *MockSession_Exited_Call {
	_c.Call.Return(run)
	return _c
}

// Hover provides a mock function for the type MockSession
func (_mock *MockSession) Hover(ctx context.Context, path string, line int, char int) (string, error) {
	ret := _mock.Called(ctx, path, line, char)

	if len(ret) == 0 {
		panic("no return value specified for Hover")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (string, error)); ok {
		return returnFunc(ctx, path, line, char)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) string); ok {
		r0 = returnFunc(ctx, path, line, char)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, path, line, char)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_Hover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hover'
type MockSession_Hover_Call struct {
	*mock.Call
}

// Hover is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - line int
//   - char int
func (_e *MockSession_Expecter) Hover(ctx interface{}, path interface{}, line interface{}, char interface{}) *MockSession_Hover_Call {
	return &MockSession_Hover_Call{Call: _e.mock.On("Hover", ctx, path, line, char)}
}

func (_c *MockSession_Hover_Call) Run(run func(ctx context.Context, path string, line int, char int)) *MockSession_Hover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSession_Hover_Call) Return(s string, err error) *MockSession_Hover_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSession_Hover_Call) RunAndReturn(run func(ctx context.Context, path string, line int, char int) (string, error)) *MockSession_Hover_Call {
	_c.Call.Return(run)
	return _c
}

// Notifications provides a mock function for the type MockSession
func (_mock *MockSession) Notifications() <-chan lsp.Notification {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Notifications")
	}

	var r0 <-chan lsp.Notification
	if returnFunc, ok := ret.Get(0).(func() <-chan lsp.Notification); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan lsp.Notification)
		}
	}
	return r0
}

// MockSession_Notifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notifications'
type MockSession_Notifications_Call struct {
	*mock.Call
}

// Notifications is a helper method to define mock.On call
func (_e *MockSession_Expecter) Notifications() *MockSession_Notifications_Call {
	return &MockSession_Notifications_Call{Call: _e.mock.On("Notifications")}
}

func (_c *MockSession_Notifications_Call) Run(run func()) *MockSession_Notifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_Notifications_Call) Return(notificationCh <-chan lsp.Notification) *MockSession_Notifications_Call {
	_c.Call.Return(notificationCh)
	return _c
}

func (_c *MockSession_Notifications_Call) RunAndReturn(run func() <-chan lsp.Notification) *MockSession_Notifications_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockSession
func (_mock *MockSession) Shutdown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockSession_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockSession_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSession_Expecter) Shutdown(ctx interface{}) *MockSession_Shutdown_Call {
	return &MockSession_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockSession_Shutdown_Call) Run(run func(ctx context.Context)) *MockSession_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_Shutdown_Call) Return() *MockSession_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSession_Shutdown_Call) RunAndReturn(run func(ctx context.Context)) *MockSession_Shutdown_Call {
	_c.Run(run)
	return _c
}
