// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockBuffer creates a new instance of MockBuffer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBuffer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBuffer {
	mock := &MockBuffer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBuffer is an autogenerated mock type for the Buffer type
type MockBuffer struct {
	mock.Mock
}

type MockBuffer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBuffer) EXPECT() *MockBuffer_Expecter {
	return &MockBuffer_Expecter{mock: &_m.Mock}
}

// DeleteAfter provides a mock function for the type MockBuffer
func (_mock *MockBuffer) DeleteAfter(n int) {
	_mock.Called(n)
	return
}

// MockBuffer_DeleteAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAfter'
type MockBuffer_DeleteAfter_Call struct {
	*mock.Call
}

// DeleteAfter is a helper method to define mock.On call
//   - n int
func (_e *MockBuffer_Expecter) DeleteAfter(n interface{}) *MockBuffer_DeleteAfter_Call {
	return &MockBuffer_DeleteAfter_Call{Call: _e.mock.On("DeleteAfter", n)}
}

func (_c *MockBuffer_DeleteAfter_Call) Run(run func(n int)) *MockBuffer_DeleteAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBuffer_DeleteAfter_Call) Return() *MockBuffer_DeleteAfter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_DeleteAfter_Call) RunAndReturn(run func(n int)) *MockBuffer_DeleteAfter_Call {
	_c.Run(run)
	return _c
}

// DeleteBefore provides a mock function for the type MockBuffer
func (_mock *MockBuffer) DeleteBefore(n int) {
	_mock.Called(n)
	return
}

// MockBuffer_DeleteBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBefore'
type MockBuffer_DeleteBefore_Call struct {
	*mock.Call
}

// DeleteBefore is a helper method to define mock.On call
//   - n int
func (_e *MockBuffer_Expecter) DeleteBefore(n interface{}) *MockBuffer_DeleteBefore_Call {
	return &MockBuffer_DeleteBefore_Call{Call: _e.mock.On("DeleteBefore", n)}
}

func (_c *MockBuffer_DeleteBefore_Call) Run(run func(n int)) *MockBuffer_DeleteBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBuffer_DeleteBefore_Call) Return() *MockBuffer_DeleteBefore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_DeleteBefore_Call) RunAndReturn(run func(n int)) *MockBuffer_DeleteBefore_Call {
	_c.Run(run)
	return _c
}

// DeleteRange provides a mock function for the type MockBuffer
func (_mock *MockBuffer) DeleteRange(start int, end int) {
	_mock.Called(start, end)
	return
}

// MockBuffer_DeleteRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRange'
type MockBuffer_DeleteRange_Call struct {
	*mock.Call
}

// DeleteRange is a helper method to define mock.On call
//   - start int
//   - end int
func (_e *MockBuffer_Expecter) DeleteRange(start interface{}, end interface{}) *MockBuffer_DeleteRange_Call {
	return &MockBuffer_DeleteRange_Call{Call: _e.mock.On("DeleteRange", start, end)}
}

func (_c *MockBuffer_DeleteRange_Call) Run(run func(start int, end int)) *MockBuffer_DeleteRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBuffer_DeleteRange_Call) Return() *MockBuffer_DeleteRange_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_DeleteRange_Call) RunAndReturn(run func(start int, end int)) *MockBuffer_DeleteRange_Call {
	_c.Run(run)
	return _c
}

// GapStart provides a mock function for the type MockBuffer
func (_mock *MockBuffer) GapStart() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GapStart")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockBuffer_GapStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GapStart'
type MockBuffer_GapStart_Call struct {
	*mock.Call
}

// GapStart is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) GapStart() *MockBuffer_GapStart_Call {
	return &MockBuffer_GapStart_Call{Call: _e.mock.On("GapStart")}
}

func (_c *MockBuffer_GapStart_Call) Run(run func()) *MockBuffer_GapStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_GapStart_Call) Return(n int) *MockBuffer_GapStart_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockBuffer_GapStart_Call) RunAndReturn(run func() int) *MockBuffer_GapStart_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockBuffer
func (_mock *MockBuffer) Insert(r rune) {
	_mock.Called(r)
	return
}

// MockBuffer_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockBuffer_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - r rune
func (_e *MockBuffer_Expecter) Insert(r interface{}) *MockBuffer_Insert_Call {
	return &MockBuffer_Insert_Call{Call: _e.mock.On("Insert", r)}
}

func (_c *MockBuffer_Insert_Call) Run(run func(r rune)) *MockBuffer_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rune
		if args[0] != nil {
			arg0 = args[0].(rune)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBuffer_Insert_Call) Return() *MockBuffer_Insert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_Insert_Call) RunAndReturn(run func(r rune)) *MockBuffer_Insert_Call {
	_c.Run(run)
	return _c
}

// InsertAt provides a mock function for the type MockBuffer
func (_mock *MockBuffer) InsertAt(pos int, r rune) {
	_mock.Called(pos, r)
	return
}

// MockBuffer_InsertAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAt'
type MockBuffer_InsertAt_Call struct {
	*mock.Call
}

// InsertAt is a helper method to define mock.On call
//   - pos int
//   - r rune
func (_e *MockBuffer_Expecter) InsertAt(pos interface{}, r interface{}) *MockBuffer_InsertAt_Call {
	return &MockBuffer_InsertAt_Call{Call: _e.mock.On("InsertAt", pos, r)}
}

func (_c *MockBuffer_InsertAt_Call) Run(run func(pos int, r rune)) *MockBuffer_InsertAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 rune
		if args[1] != nil {
			arg1 = args[1].(rune)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBuffer_InsertAt_Call) Return() *MockBuffer_InsertAt_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_InsertAt_Call) RunAndReturn(run func(pos int, r rune)) *MockBuffer_InsertAt_Call {
	_c.Run(run)
	return _c
}

// InsertSlice provides a mock function for the type MockBuffer
func (_mock *MockBuffer) InsertSlice(runes []rune) {
	_mock.Called(runes)
	return
}

// MockBuffer_InsertSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSlice'
type MockBuffer_InsertSlice_Call struct {
	*mock.Call
}

// InsertSlice is a helper method to define mock.On call
//   - runes []rune
func (_e *MockBuffer_Expecter) InsertSlice(runes interface{}) *MockBuffer_InsertSlice_Call {
	return &MockBuffer_InsertSlice_Call{Call: _e.mock.On("InsertSlice", runes)}
}

func (_c *MockBuffer_InsertSlice_Call) Run(run func(runes []rune)) *MockBuffer_InsertSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []rune
		if args[0] != nil {
			arg0 = args[0].([]rune)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBuffer_InsertSlice_Call) Return() *MockBuffer_InsertSlice_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_InsertSlice_Call) RunAndReturn(run func(runes []rune)) *MockBuffer_InsertSlice_Call {
	_c.Run(run)
	return _c
}

// Len provides a mock function for the type MockBuffer
func (_mock *MockBuffer) Len() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockBuffer_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockBuffer_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Len() *MockBuffer_Len_Call {
	return &MockBuffer_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockBuffer_Len_Call) Run(run func()) *MockBuffer_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Len_Call) Return(n int) *MockBuffer_Len_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockBuffer_Len_Call) RunAndReturn(run func() int) *MockBuffer_Len_Call {
	_c.Call.Return(run)
	return _c
}

// MoveTo provides a mock function for the type MockBuffer
func (_mock *MockBuffer) MoveTo(pos int) {
	_mock.Called(pos)
	return
}

// MockBuffer_MoveTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveTo'
type MockBuffer_MoveTo_Call struct {
	*mock.Call
}

// MoveTo is a helper method to define mock.On call
//   - pos int
func (_e *MockBuffer_Expecter) MoveTo(pos interface{}) *MockBuffer_MoveTo_Call {
	return &MockBuffer_MoveTo_Call{Call: _e.mock.On("MoveTo", pos)}
}

func (_c *MockBuffer_MoveTo_Call) Run(run func(pos int)) *MockBuffer_MoveTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBuffer_MoveTo_Call) Return() *MockBuffer_MoveTo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_MoveTo_Call) RunAndReturn(run func(pos int)) *MockBuffer_MoveTo_Call {
	_c.Run(run)
	return _c
}

// Rune provides a mock function for the type MockBuffer
func (_mock *MockBuffer) Rune(i int) rune {
	ret := _mock.Called(i)

	if len(ret) == 0 {
		panic("no return value specified for Rune")
	}

	var r0 rune
	if returnFunc, ok := ret.Get(0).(func(int) rune); ok {
		r0 = returnFunc(i)
	} else {
		r0 = ret.Get(0).(rune)
	}
	return r0
}

// MockBuffer_Rune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rune'
type MockBuffer_Rune_Call struct {
	*mock.Call
}

// Rune is a helper method to define mock.On call
//   - i int
func (_e *MockBuffer_Expecter) Rune(i interface{}) *MockBuffer_Rune_Call {
	return &MockBuffer_Rune_Call{Call: _e.mock.On("Rune", i)}
}

func (_c *MockBuffer_Rune_Call) Run(run func(i int)) *MockBuffer_Rune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBuffer_Rune_Call) Return(n rune) *MockBuffer_Rune_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockBuffer_Rune_Call) RunAndReturn(run func(i int) rune) *MockBuffer_Rune_Call {
	_c.Call.Return(run)
	return _c
}

// Slice provides a mock function for the type MockBuffer
func (_mock *MockBuffer) Slice(start int, end int) []rune {
	ret := _mock.Called(start, end)

	if len(ret) == 0 {
		panic("no return value specified for Slice")
	}

	var r0 []rune
	if returnFunc, ok := ret.Get(0).(func(int, int) []rune); ok {
		r0 = returnFunc(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rune)
		}
	}
	return r0
}

// MockBuffer_Slice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slice'
type MockBuffer_Slice_Call struct {
	*mock.Call
}

// Slice is a helper method to define mock.On call
//   - start int
//   - end int
func (_e *MockBuffer_Expecter) Slice(start interface{}, end interface{}) *MockBuffer_Slice_Call {
	return &MockBuffer_Slice_Call{Call: _e.mock.On("Slice", start, end)}
}

func (_c *MockBuffer_Slice_Call) Run(run func(start int, end int)) *MockBuffer_Slice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBuffer_Slice_Call) Return(runes []rune) *MockBuffer_Slice_Call {
	_c.Call.Return(runes)
	return _c
}

func (_c *MockBuffer_Slice_Call) RunAndReturn(run func(start int, end int) []rune) *MockBuffer_Slice_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockBuffer
func (_mock *MockBuffer) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBuffer_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockBuffer_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) String() *MockBuffer_String_Call {
	return &MockBuffer_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockBuffer_String_Call) Run(run func()) *MockBuffer_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_String_Call) Return(s string) *MockBuffer_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBuffer_String_Call) RunAndReturn(run func() string) *MockBuffer_String_Call {
	_c.Call.Return(run)
	return _c
}

// Text provides a mock function for the type MockBuffer
func (_mock *MockBuffer) Text() []rune {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Text")
	}

	var r0 []rune
	if returnFunc, ok := ret.Get(0).(func() []rune); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rune)
		}
	}
	return r0
}

// MockBuffer_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type MockBuffer_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Text() *MockBuffer_Text_Call {
	return &MockBuffer_Text_Call{Call: _e.mock.On("Text")}
}

func (_c *MockBuffer_Text_Call) Run(run func()) *MockBuffer_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Text_Call) Return(runes []rune) *MockBuffer_Text_Call {
	_c.Call.Return(runes)
	return _c
}

func (_c *MockBuffer_Text_Call) RunAndReturn(run func() []rune) *MockBuffer_Text_Call {
	_c.Call.Return(run)
	return _c
}
