// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	buffer "github.com/anthonybrice/editor/internal/buffer"
	editor "github.com/anthonybrice/editor/internal/editor"

	mock "github.com/stretchr/testify/mock"
)

// MockEditor is an autogenerated mock type for the Editor type
type MockEditor struct {
	mock.Mock
}

type MockEditor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditor) EXPECT() *MockEditor_Expecter {
	return &MockEditor_Expecter{mock: &_m.Mock}
}

// Buf provides a mock function with no fields
func (_m *MockEditor) Buf() buffer.Buffer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Buf")
	}

	var r0 buffer.Buffer
	if rf, ok := ret.Get(0).(func() buffer.Buffer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(buffer.Buffer)
		}
	}

	return r0
}

// MockEditor_Buf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Buf'
type MockEditor_Buf_Call struct {
	*mock.Call
}

// Buf is a helper method to define mock.On call
func (_e *MockEditor_Expecter) Buf() *MockEditor_Buf_Call {
	return &MockEditor_Buf_Call{Call: _e.mock.On("Buf")}
}

func (_c *MockEditor_Buf_Call) Run(run func()) *MockEditor_Buf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_Buf_Call) Return(_a0 buffer.Buffer) *MockEditor_Buf_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_Buf_Call) RunAndReturn(run func() buffer.Buffer) *MockEditor_Buf_Call {
	_c.Call.Return(run)
	return _c
}

// CmdBuf provides a mock function with no fields
func (_m *MockEditor) CmdBuf() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CmdBuf")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEditor_CmdBuf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CmdBuf'
type MockEditor_CmdBuf_Call struct {
	*mock.Call
}

// CmdBuf is a helper method to define mock.On call
func (_e *MockEditor_Expecter) CmdBuf() *MockEditor_CmdBuf_Call {
	return &MockEditor_CmdBuf_Call{Call: _e.mock.On("CmdBuf")}
}

func (_c *MockEditor_CmdBuf_Call) Run(run func()) *MockEditor_CmdBuf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_CmdBuf_Call) Return(_a0 string) *MockEditor_CmdBuf_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_CmdBuf_Call) RunAndReturn(run func() string) *MockEditor_CmdBuf_Call {
	_c.Call.Return(run)
	return _c
}

// CmdMode provides a mock function with no fields
func (_m *MockEditor) CmdMode() rune {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CmdMode")
	}

	var r0 rune
	if rf, ok := ret.Get(0).(func() rune); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(rune)
	}

	return r0
}

// MockEditor_CmdMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CmdMode'
type MockEditor_CmdMode_Call struct {
	*mock.Call
}

// CmdMode is a helper method to define mock.On call
func (_e *MockEditor_Expecter) CmdMode() *MockEditor_CmdMode_Call {
	return &MockEditor_CmdMode_Call{Call: _e.mock.On("CmdMode")}
}

func (_c *MockEditor_CmdMode_Call) Run(run func()) *MockEditor_CmdMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_CmdMode_Call) Return(_a0 rune) *MockEditor_CmdMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_CmdMode_Call) RunAndReturn(run func() rune) *MockEditor_CmdMode_Call {
	_c.Call.Return(run)
	return _c
}

// Cursor provides a mock function with no fields
func (_m *MockEditor) Cursor() editor.Pos {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cursor")
	}

	var r0 editor.Pos
	if rf, ok := ret.Get(0).(func() editor.Pos); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(editor.Pos)
	}

	return r0
}

// MockEditor_Cursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cursor'
type MockEditor_Cursor_Call struct {
	*mock.Call
}

// Cursor is a helper method to define mock.On call
func (_e *MockEditor_Expecter) Cursor() *MockEditor_Cursor_Call {
	return &MockEditor_Cursor_Call{Call: _e.mock.On("Cursor")}
}

func (_c *MockEditor_Cursor_Call) Run(run func()) *MockEditor_Cursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_Cursor_Call) Return(_a0 editor.Pos) *MockEditor_Cursor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_Cursor_Call) RunAndReturn(run func() editor.Pos) *MockEditor_Cursor_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiagnostics provides a mock function with no fields
func (_m *MockEditor) GetDiagnostics() []editor.Diagnostic {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDiagnostics")
	}

	var r0 []editor.Diagnostic
	if rf, ok := ret.Get(0).(func() []editor.Diagnostic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]editor.Diagnostic)
		}
	}

	return r0
}

// MockEditor_GetDiagnostics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiagnostics'
type MockEditor_GetDiagnostics_Call struct {
	*mock.Call
}

// GetDiagnostics is a helper method to define mock.On call
func (_e *MockEditor_Expecter) GetDiagnostics() *MockEditor_GetDiagnostics_Call {
	return &MockEditor_GetDiagnostics_Call{Call: _e.mock.On("GetDiagnostics")}
}

func (_c *MockEditor_GetDiagnostics_Call) Run(run func()) *MockEditor_GetDiagnostics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_GetDiagnostics_Call) Return(_a0 []editor.Diagnostic) *MockEditor_GetDiagnostics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_GetDiagnostics_Call) RunAndReturn(run func() []editor.Diagnostic) *MockEditor_GetDiagnostics_Call {
	_c.Call.Return(run)
	return _c
}

// HandleKey provides a mock function with given fields: key
func (_m *MockEditor) HandleKey(key string) {
	_m.Called(key)
}

// MockEditor_HandleKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleKey'
type MockEditor_HandleKey_Call struct {
	*mock.Call
}

// HandleKey is a helper method to define mock.On call
//   - key string
func (_e *MockEditor_Expecter) HandleKey(key interface{}) *MockEditor_HandleKey_Call {
	return &MockEditor_HandleKey_Call{Call: _e.mock.On("HandleKey", key)}
}

func (_c *MockEditor_HandleKey_Call) Run(run func(key string)) *MockEditor_HandleKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEditor_HandleKey_Call) Return() *MockEditor_HandleKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEditor_HandleKey_Call) RunAndReturn(run func(string)) *MockEditor_HandleKey_Call {
	_c.Run(run)
	return _c
}

// Mode provides a mock function with no fields
func (_m *MockEditor) Mode() editor.Mode {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 editor.Mode
	if rf, ok := ret.Get(0).(func() editor.Mode); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(editor.Mode)
	}

	return r0
}

// MockEditor_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockEditor_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockEditor_Expecter) Mode() *MockEditor_Mode_Call {
	return &MockEditor_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockEditor_Mode_Call) Run(run func()) *MockEditor_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_Mode_Call) Return(_a0 editor.Mode) *MockEditor_Mode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_Mode_Call) RunAndReturn(run func() editor.Mode) *MockEditor_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// SetDiagnostics provides a mock function with given fields: d
func (_m *MockEditor) SetDiagnostics(d []editor.Diagnostic) {
	_m.Called(d)
}

// MockEditor_SetDiagnostics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDiagnostics'
type MockEditor_SetDiagnostics_Call struct {
	*mock.Call
}

// SetDiagnostics is a helper method to define mock.On call
//   - d []editor.Diagnostic
func (_e *MockEditor_Expecter) SetDiagnostics(d interface{}) *MockEditor_SetDiagnostics_Call {
	return &MockEditor_SetDiagnostics_Call{Call: _e.mock.On("SetDiagnostics", d)}
}

func (_c *MockEditor_SetDiagnostics_Call) Run(run func(d []editor.Diagnostic)) *MockEditor_SetDiagnostics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]editor.Diagnostic))
	})
	return _c
}

func (_c *MockEditor_SetDiagnostics_Call) Return() *MockEditor_SetDiagnostics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEditor_SetDiagnostics_Call) RunAndReturn(run func([]editor.Diagnostic)) *MockEditor_SetDiagnostics_Call {
	_c.Run(run)
	return _c
}

// StatusMsg provides a mock function with no fields
func (_m *MockEditor) StatusMsg() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusMsg")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEditor_StatusMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusMsg'
type MockEditor_StatusMsg_Call struct {
	*mock.Call
}

// StatusMsg is a helper method to define mock.On call
func (_e *MockEditor_Expecter) StatusMsg() *MockEditor_StatusMsg_Call {
	return &MockEditor_StatusMsg_Call{Call: _e.mock.On("StatusMsg")}
}

func (_c *MockEditor_StatusMsg_Call) Run(run func()) *MockEditor_StatusMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_StatusMsg_Call) Return(_a0 string) *MockEditor_StatusMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_StatusMsg_Call) RunAndReturn(run func() string) *MockEditor_StatusMsg_Call {
	_c.Call.Return(run)
	return _c
}

// VisualAnchor provides a mock function with no fields
func (_m *MockEditor) VisualAnchor() editor.Pos {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VisualAnchor")
	}

	var r0 editor.Pos
	if rf, ok := ret.Get(0).(func() editor.Pos); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(editor.Pos)
	}

	return r0
}

// MockEditor_VisualAnchor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisualAnchor'
type MockEditor_VisualAnchor_Call struct {
	*mock.Call
}

// VisualAnchor is a helper method to define mock.On call
func (_e *MockEditor_Expecter) VisualAnchor() *MockEditor_VisualAnchor_Call {
	return &MockEditor_VisualAnchor_Call{Call: _e.mock.On("VisualAnchor")}
}

func (_c *MockEditor_VisualAnchor_Call) Run(run func()) *MockEditor_VisualAnchor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_VisualAnchor_Call) Return(_a0 editor.Pos) *MockEditor_VisualAnchor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_VisualAnchor_Call) RunAndReturn(run func() editor.Pos) *MockEditor_VisualAnchor_Call {
	_c.Call.Return(run)
	return _c
}

// VisualRange provides a mock function with no fields
func (_m *MockEditor) VisualRange() (editor.Pos, editor.Pos) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VisualRange")
	}

	var r0 editor.Pos
	var r1 editor.Pos
	if rf, ok := ret.Get(0).(func() (editor.Pos, editor.Pos)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() editor.Pos); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(editor.Pos)
	}

	if rf, ok := ret.Get(1).(func() editor.Pos); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(editor.Pos)
	}

	return r0, r1
}

// MockEditor_VisualRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisualRange'
type MockEditor_VisualRange_Call struct {
	*mock.Call
}

// VisualRange is a helper method to define mock.On call
func (_e *MockEditor_Expecter) VisualRange() *MockEditor_VisualRange_Call {
	return &MockEditor_VisualRange_Call{Call: _e.mock.On("VisualRange")}
}

func (_c *MockEditor_VisualRange_Call) Run(run func()) *MockEditor_VisualRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_VisualRange_Call) Return(start editor.Pos, end editor.Pos) *MockEditor_VisualRange_Call {
	_c.Call.Return(start, end)
	return _c
}

func (_c *MockEditor_VisualRange_Call) RunAndReturn(run func() (editor.Pos, editor.Pos)) *MockEditor_VisualRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEditor creates a new instance of MockEditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEditor {
	mock := &MockEditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
