// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockstore

import (
	piece "github.com/anthonybrice/editor/internal/buffer/piece"
	mock "github.com/stretchr/testify/mock"
)

// MockUndoStore is an autogenerated mock type for the UndoStore type
type MockUndoStore struct {
	mock.Mock
}

type MockUndoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUndoStore) EXPECT() *MockUndoStore_Expecter {
	return &MockUndoStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockUndoStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUndoStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockUndoStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockUndoStore_Expecter) Close() *MockUndoStore_Close_Call {
	return &MockUndoStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockUndoStore_Close_Call) Run(run func()) *MockUndoStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUndoStore_Close_Call) Return(_a0 error) *MockUndoStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUndoStore_Close_Call) RunAndReturn(run func() error) *MockUndoStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function with no fields
func (_m *MockUndoStore) Current() piece.Snapshot {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 piece.Snapshot
	if rf, ok := ret.Get(0).(func() piece.Snapshot); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(piece.Snapshot)
	}

	return r0
}

// MockUndoStore_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockUndoStore_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
func (_e *MockUndoStore_Expecter) Current() *MockUndoStore_Current_Call {
	return &MockUndoStore_Current_Call{Call: _e.mock.On("Current")}
}

func (_c *MockUndoStore_Current_Call) Run(run func()) *MockUndoStore_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUndoStore_Current_Call) Return(_a0 piece.Snapshot) *MockUndoStore_Current_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUndoStore_Current_Call) RunAndReturn(run func() piece.Snapshot) *MockUndoStore_Current_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function with given fields: snap
func (_m *MockUndoStore) Push(snap piece.Snapshot) error {
	ret := _m.Called(snap)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(piece.Snapshot) error); ok {
		r0 = rf(snap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUndoStore_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockUndoStore_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - snap piece.Snapshot
func (_e *MockUndoStore_Expecter) Push(snap interface{}) *MockUndoStore_Push_Call {
	return &MockUndoStore_Push_Call{Call: _e.mock.On("Push", snap)}
}

func (_c *MockUndoStore_Push_Call) Run(run func(snap piece.Snapshot)) *MockUndoStore_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(piece.Snapshot))
	})
	return _c
}

func (_c *MockUndoStore_Push_Call) Return(_a0 error) *MockUndoStore_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUndoStore_Push_Call) RunAndReturn(run func(piece.Snapshot) error) *MockUndoStore_Push_Call {
	_c.Call.Return(run)
	return _c
}

// Redo provides a mock function with no fields
func (_m *MockUndoStore) Redo() (piece.Snapshot, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Redo")
	}

	var r0 piece.Snapshot
	var r1 bool
	if rf, ok := ret.Get(0).(func() (piece.Snapshot, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() piece.Snapshot); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(piece.Snapshot)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockUndoStore_Redo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redo'
type MockUndoStore_Redo_Call struct {
	*mock.Call
}

// Redo is a helper method to define mock.On call
func (_e *MockUndoStore_Expecter) Redo() *MockUndoStore_Redo_Call {
	return &MockUndoStore_Redo_Call{Call: _e.mock.On("Redo")}
}

func (_c *MockUndoStore_Redo_Call) Run(run func()) *MockUndoStore_Redo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUndoStore_Redo_Call) Return(_a0 piece.Snapshot, _a1 bool) *MockUndoStore_Redo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUndoStore_Redo_Call) RunAndReturn(run func() (piece.Snapshot, bool)) *MockUndoStore_Redo_Call {
	_c.Call.Return(run)
	return _c
}

// Undo provides a mock function with no fields
func (_m *MockUndoStore) Undo() (piece.Snapshot, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Undo")
	}

	var r0 piece.Snapshot
	var r1 bool
	if rf, ok := ret.Get(0).(func() (piece.Snapshot, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() piece.Snapshot); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(piece.Snapshot)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockUndoStore_Undo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Undo'
type MockUndoStore_Undo_Call struct {
	*mock.Call
}

// Undo is a helper method to define mock.On call
func (_e *MockUndoStore_Expecter) Undo() *MockUndoStore_Undo_Call {
	return &MockUndoStore_Undo_Call{Call: _e.mock.On("Undo")}
}

func (_c *MockUndoStore_Undo_Call) Run(run func()) *MockUndoStore_Undo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUndoStore_Undo_Call) Return(_a0 piece.Snapshot, _a1 bool) *MockUndoStore_Undo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUndoStore_Undo_Call) RunAndReturn(run func() (piece.Snapshot, bool)) *MockUndoStore_Undo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUndoStore creates a new instance of MockUndoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUndoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUndoStore {
	mock := &MockUndoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
