// Code generated by mockery v2.53.5. DO NOT EDIT.

package buffer

import mock "github.com/stretchr/testify/mock"

// MockBuffer is an autogenerated mock type for the Buffer type
type MockBuffer struct {
	mock.Mock
}

type MockBuffer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBuffer) EXPECT() *MockBuffer_Expecter {
	return &MockBuffer_Expecter{mock: &_m.Mock}
}

// ActivateGap provides a mock function with given fields: row, col
func (_m *MockBuffer) ActivateGap(row int, col int) {
	_m.Called(row, col)
}

// MockBuffer_ActivateGap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateGap'
type MockBuffer_ActivateGap_Call struct {
	*mock.Call
}

// ActivateGap is a helper method to define mock.On call
//   - row int
//   - col int
func (_e *MockBuffer_Expecter) ActivateGap(row interface{}, col interface{}) *MockBuffer_ActivateGap_Call {
	return &MockBuffer_ActivateGap_Call{Call: _e.mock.On("ActivateGap", row, col)}
}

func (_c *MockBuffer_ActivateGap_Call) Run(run func(row int, col int)) *MockBuffer_ActivateGap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBuffer_ActivateGap_Call) Return() *MockBuffer_ActivateGap_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_ActivateGap_Call) RunAndReturn(run func(int, int)) *MockBuffer_ActivateGap_Call {
	_c.Run(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockBuffer) Close() {
	_m.Called()
}

// MockBuffer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBuffer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Close() *MockBuffer_Close_Call {
	return &MockBuffer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBuffer_Close_Call) Run(run func()) *MockBuffer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Close_Call) Return() *MockBuffer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_Close_Call) RunAndReturn(run func()) *MockBuffer_Close_Call {
	_c.Run(run)
	return _c
}

// DeleteBack provides a mock function with given fields: row, col
func (_m *MockBuffer) DeleteBack(row int, col int) (int, int) {
	ret := _m.Called(row, col)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBack")
	}

	var r0 int
	var r1 int
	if rf, ok := ret.Get(0).(func(int, int) (int, int)); ok {
		return rf(row, col)
	}
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(row, col)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(row, col)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// MockBuffer_DeleteBack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBack'
type MockBuffer_DeleteBack_Call struct {
	*mock.Call
}

// DeleteBack is a helper method to define mock.On call
//   - row int
//   - col int
func (_e *MockBuffer_Expecter) DeleteBack(row interface{}, col interface{}) *MockBuffer_DeleteBack_Call {
	return &MockBuffer_DeleteBack_Call{Call: _e.mock.On("DeleteBack", row, col)}
}

func (_c *MockBuffer_DeleteBack_Call) Run(run func(row int, col int)) *MockBuffer_DeleteBack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBuffer_DeleteBack_Call) Return(newRow int, newCol int) *MockBuffer_DeleteBack_Call {
	_c.Call.Return(newRow, newCol)
	return _c
}

func (_c *MockBuffer_DeleteBack_Call) RunAndReturn(run func(int, int) (int, int)) *MockBuffer_DeleteBack_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLines provides a mock function with given fields: r1, r2
func (_m *MockBuffer) DeleteLines(r1 int, r2 int) {
	_m.Called(r1, r2)
}

// MockBuffer_DeleteLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLines'
type MockBuffer_DeleteLines_Call struct {
	*mock.Call
}

// DeleteLines is a helper method to define mock.On call
//   - r1 int
//   - r2 int
func (_e *MockBuffer_Expecter) DeleteLines(r1 interface{}, r2 interface{}) *MockBuffer_DeleteLines_Call {
	return &MockBuffer_DeleteLines_Call{Call: _e.mock.On("DeleteLines", r1, r2)}
}

func (_c *MockBuffer_DeleteLines_Call) Run(run func(r1 int, r2 int)) *MockBuffer_DeleteLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBuffer_DeleteLines_Call) Return() *MockBuffer_DeleteLines_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_DeleteLines_Call) RunAndReturn(run func(int, int)) *MockBuffer_DeleteLines_Call {
	_c.Run(run)
	return _c
}

// DeleteRange provides a mock function with given fields: r1, c1, r2, c2
func (_m *MockBuffer) DeleteRange(r1 int, c1 int, r2 int, c2 int) (int, int) {
	ret := _m.Called(r1, c1, r2, c2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRange")
	}

	var retRow int
	var retCol int
	if rf, ok := ret.Get(0).(func(int, int, int, int) (int, int)); ok {
		return rf(r1, c1, r2, c2)
	}
	if rf, ok := ret.Get(0).(func(int, int, int, int) int); ok {
		retRow = rf(r1, c1, r2, c2)
	} else {
		retRow = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int, int, int) int); ok {
		retCol = rf(r1, c1, r2, c2)
	} else {
		retCol = ret.Get(1).(int)
	}

	return retRow, retCol
}

// MockBuffer_DeleteRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRange'
type MockBuffer_DeleteRange_Call struct {
	*mock.Call
}

// DeleteRange is a helper method to define mock.On call
//   - r1 int
//   - c1 int
//   - r2 int
//   - c2 int
func (_e *MockBuffer_Expecter) DeleteRange(r1 interface{}, c1 interface{}, r2 interface{}, c2 interface{}) *MockBuffer_DeleteRange_Call {
	return &MockBuffer_DeleteRange_Call{Call: _e.mock.On("DeleteRange", r1, c1, r2, c2)}
}

func (_c *MockBuffer_DeleteRange_Call) Run(run func(r1 int, c1 int, r2 int, c2 int)) *MockBuffer_DeleteRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockBuffer_DeleteRange_Call) Return(row int, col int) *MockBuffer_DeleteRange_Call {
	_c.Call.Return(row, col)
	return _c
}

func (_c *MockBuffer_DeleteRange_Call) RunAndReturn(run func(int, int, int, int) (int, int)) *MockBuffer_DeleteRange_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRune provides a mock function with given fields: row, col
func (_m *MockBuffer) DeleteRune(row int, col int) bool {
	ret := _m.Called(row, col)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRune")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(row, col)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBuffer_DeleteRune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRune'
type MockBuffer_DeleteRune_Call struct {
	*mock.Call
}

// DeleteRune is a helper method to define mock.On call
//   - row int
//   - col int
func (_e *MockBuffer_Expecter) DeleteRune(row interface{}, col interface{}) *MockBuffer_DeleteRune_Call {
	return &MockBuffer_DeleteRune_Call{Call: _e.mock.On("DeleteRune", row, col)}
}

func (_c *MockBuffer_DeleteRune_Call) Run(run func(row int, col int)) *MockBuffer_DeleteRune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBuffer_DeleteRune_Call) Return(_a0 bool) *MockBuffer_DeleteRune_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_DeleteRune_Call) RunAndReturn(run func(int, int) bool) *MockBuffer_DeleteRune_Call {
	_c.Call.Return(run)
	return _c
}

// FlushGap provides a mock function with no fields
func (_m *MockBuffer) FlushGap() {
	_m.Called()
}

// MockBuffer_FlushGap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushGap'
type MockBuffer_FlushGap_Call struct {
	*mock.Call
}

// FlushGap is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) FlushGap() *MockBuffer_FlushGap_Call {
	return &MockBuffer_FlushGap_Call{Call: _e.mock.On("FlushGap")}
}

func (_c *MockBuffer_FlushGap_Call) Run(run func()) *MockBuffer_FlushGap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_FlushGap_Call) Return() *MockBuffer_FlushGap_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_FlushGap_Call) RunAndReturn(run func()) *MockBuffer_FlushGap_Call {
	_c.Run(run)
	return _c
}

// HasUndoStore provides a mock function with no fields
func (_m *MockBuffer) HasUndoStore() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasUndoStore")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBuffer_HasUndoStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasUndoStore'
type MockBuffer_HasUndoStore_Call struct {
	*mock.Call
}

// HasUndoStore is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) HasUndoStore() *MockBuffer_HasUndoStore_Call {
	return &MockBuffer_HasUndoStore_Call{Call: _e.mock.On("HasUndoStore")}
}

func (_c *MockBuffer_HasUndoStore_Call) Run(run func()) *MockBuffer_HasUndoStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_HasUndoStore_Call) Return(_a0 bool) *MockBuffer_HasUndoStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_HasUndoStore_Call) RunAndReturn(run func() bool) *MockBuffer_HasUndoStore_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: row, col, r
func (_m *MockBuffer) Insert(row int, col int, r rune) {
	_m.Called(row, col, r)
}

// MockBuffer_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockBuffer_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - row int
//   - col int
//   - r rune
func (_e *MockBuffer_Expecter) Insert(row interface{}, col interface{}, r interface{}) *MockBuffer_Insert_Call {
	return &MockBuffer_Insert_Call{Call: _e.mock.On("Insert", row, col, r)}
}

func (_c *MockBuffer_Insert_Call) Run(run func(row int, col int, r rune)) *MockBuffer_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(rune))
	})
	return _c
}

func (_c *MockBuffer_Insert_Call) Return() *MockBuffer_Insert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_Insert_Call) RunAndReturn(run func(int, int, rune)) *MockBuffer_Insert_Call {
	_c.Run(run)
	return _c
}

// InsertLineAbove provides a mock function with given fields: row
func (_m *MockBuffer) InsertLineAbove(row int) int {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for InsertLineAbove")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBuffer_InsertLineAbove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLineAbove'
type MockBuffer_InsertLineAbove_Call struct {
	*mock.Call
}

// InsertLineAbove is a helper method to define mock.On call
//   - row int
func (_e *MockBuffer_Expecter) InsertLineAbove(row interface{}) *MockBuffer_InsertLineAbove_Call {
	return &MockBuffer_InsertLineAbove_Call{Call: _e.mock.On("InsertLineAbove", row)}
}

func (_c *MockBuffer_InsertLineAbove_Call) Run(run func(row int)) *MockBuffer_InsertLineAbove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBuffer_InsertLineAbove_Call) Return(_a0 int) *MockBuffer_InsertLineAbove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_InsertLineAbove_Call) RunAndReturn(run func(int) int) *MockBuffer_InsertLineAbove_Call {
	_c.Call.Return(run)
	return _c
}

// InsertLineBelow provides a mock function with given fields: row
func (_m *MockBuffer) InsertLineBelow(row int) int {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for InsertLineBelow")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBuffer_InsertLineBelow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertLineBelow'
type MockBuffer_InsertLineBelow_Call struct {
	*mock.Call
}

// InsertLineBelow is a helper method to define mock.On call
//   - row int
func (_e *MockBuffer_Expecter) InsertLineBelow(row interface{}) *MockBuffer_InsertLineBelow_Call {
	return &MockBuffer_InsertLineBelow_Call{Call: _e.mock.On("InsertLineBelow", row)}
}

func (_c *MockBuffer_InsertLineBelow_Call) Run(run func(row int)) *MockBuffer_InsertLineBelow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBuffer_InsertLineBelow_Call) Return(_a0 int) *MockBuffer_InsertLineBelow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_InsertLineBelow_Call) RunAndReturn(run func(int) int) *MockBuffer_InsertLineBelow_Call {
	_c.Call.Return(run)
	return _c
}

// InsertString provides a mock function with given fields: row, col, s
func (_m *MockBuffer) InsertString(row int, col int, s string) {
	_m.Called(row, col, s)
}

// MockBuffer_InsertString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertString'
type MockBuffer_InsertString_Call struct {
	*mock.Call
}

// InsertString is a helper method to define mock.On call
//   - row int
//   - col int
//   - s string
func (_e *MockBuffer_Expecter) InsertString(row interface{}, col interface{}, s interface{}) *MockBuffer_InsertString_Call {
	return &MockBuffer_InsertString_Call{Call: _e.mock.On("InsertString", row, col, s)}
}

func (_c *MockBuffer_InsertString_Call) Run(run func(row int, col int, s string)) *MockBuffer_InsertString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockBuffer_InsertString_Call) Return() *MockBuffer_InsertString_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_InsertString_Call) RunAndReturn(run func(int, int, string)) *MockBuffer_InsertString_Call {
	_c.Run(run)
	return _c
}

// Line provides a mock function with given fields: row
func (_m *MockBuffer) Line(row int) string {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for Line")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBuffer_Line_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Line'
type MockBuffer_Line_Call struct {
	*mock.Call
}

// Line is a helper method to define mock.On call
//   - row int
func (_e *MockBuffer_Expecter) Line(row interface{}) *MockBuffer_Line_Call {
	return &MockBuffer_Line_Call{Call: _e.mock.On("Line", row)}
}

func (_c *MockBuffer_Line_Call) Run(run func(row int)) *MockBuffer_Line_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBuffer_Line_Call) Return(_a0 string) *MockBuffer_Line_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_Line_Call) RunAndReturn(run func(int) string) *MockBuffer_Line_Call {
	_c.Call.Return(run)
	return _c
}

// LineCount provides a mock function with no fields
func (_m *MockBuffer) LineCount() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LineCount")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBuffer_LineCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineCount'
type MockBuffer_LineCount_Call struct {
	*mock.Call
}

// LineCount is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) LineCount() *MockBuffer_LineCount_Call {
	return &MockBuffer_LineCount_Call{Call: _e.mock.On("LineCount")}
}

func (_c *MockBuffer_LineCount_Call) Run(run func()) *MockBuffer_LineCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_LineCount_Call) Return(_a0 int) *MockBuffer_LineCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_LineCount_Call) RunAndReturn(run func() int) *MockBuffer_LineCount_Call {
	_c.Call.Return(run)
	return _c
}

// LineLen provides a mock function with given fields: row
func (_m *MockBuffer) LineLen(row int) int {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for LineLen")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(row)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockBuffer_LineLen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineLen'
type MockBuffer_LineLen_Call struct {
	*mock.Call
}

// LineLen is a helper method to define mock.On call
//   - row int
func (_e *MockBuffer_Expecter) LineLen(row interface{}) *MockBuffer_LineLen_Call {
	return &MockBuffer_LineLen_Call{Call: _e.mock.On("LineLen", row)}
}

func (_c *MockBuffer_LineLen_Call) Run(run func(row int)) *MockBuffer_LineLen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBuffer_LineLen_Call) Return(_a0 int) *MockBuffer_LineLen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_LineLen_Call) RunAndReturn(run func(int) int) *MockBuffer_LineLen_Call {
	_c.Call.Return(run)
	return _c
}

// LineRunes provides a mock function with given fields: row
func (_m *MockBuffer) LineRunes(row int) []rune {
	ret := _m.Called(row)

	if len(ret) == 0 {
		panic("no return value specified for LineRunes")
	}

	var r0 []rune
	if rf, ok := ret.Get(0).(func(int) []rune); ok {
		r0 = rf(row)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rune)
		}
	}

	return r0
}

// MockBuffer_LineRunes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LineRunes'
type MockBuffer_LineRunes_Call struct {
	*mock.Call
}

// LineRunes is a helper method to define mock.On call
//   - row int
func (_e *MockBuffer_Expecter) LineRunes(row interface{}) *MockBuffer_LineRunes_Call {
	return &MockBuffer_LineRunes_Call{Call: _e.mock.On("LineRunes", row)}
}

func (_c *MockBuffer_LineRunes_Call) Run(run func(row int)) *MockBuffer_LineRunes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBuffer_LineRunes_Call) Return(_a0 []rune) *MockBuffer_LineRunes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_LineRunes_Call) RunAndReturn(run func(int) []rune) *MockBuffer_LineRunes_Call {
	_c.Call.Return(run)
	return _c
}

// Modified provides a mock function with no fields
func (_m *MockBuffer) Modified() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modified")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBuffer_Modified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modified'
type MockBuffer_Modified_Call struct {
	*mock.Call
}

// Modified is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Modified() *MockBuffer_Modified_Call {
	return &MockBuffer_Modified_Call{Call: _e.mock.On("Modified")}
}

func (_c *MockBuffer_Modified_Call) Run(run func()) *MockBuffer_Modified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Modified_Call) Return(_a0 bool) *MockBuffer_Modified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_Modified_Call) RunAndReturn(run func() bool) *MockBuffer_Modified_Call {
	_c.Call.Return(run)
	return _c
}

// Newline provides a mock function with given fields: row, col
func (_m *MockBuffer) Newline(row int, col int) {
	_m.Called(row, col)
}

// MockBuffer_Newline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Newline'
type MockBuffer_Newline_Call struct {
	*mock.Call
}

// Newline is a helper method to define mock.On call
//   - row int
//   - col int
func (_e *MockBuffer_Expecter) Newline(row interface{}, col interface{}) *MockBuffer_Newline_Call {
	return &MockBuffer_Newline_Call{Call: _e.mock.On("Newline", row, col)}
}

func (_c *MockBuffer_Newline_Call) Run(run func(row int, col int)) *MockBuffer_Newline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBuffer_Newline_Call) Return() *MockBuffer_Newline_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_Newline_Call) RunAndReturn(run func(int, int)) *MockBuffer_Newline_Call {
	_c.Run(run)
	return _c
}

// PasteAfter provides a mock function with given fields: row, col, text, linewise
func (_m *MockBuffer) PasteAfter(row int, col int, text string, linewise bool) (int, int) {
	ret := _m.Called(row, col, text, linewise)

	if len(ret) == 0 {
		panic("no return value specified for PasteAfter")
	}

	var r0 int
	var r1 int
	if rf, ok := ret.Get(0).(func(int, int, string, bool) (int, int)); ok {
		return rf(row, col, text, linewise)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, bool) int); ok {
		r0 = rf(row, col, text, linewise)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int, string, bool) int); ok {
		r1 = rf(row, col, text, linewise)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// MockBuffer_PasteAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasteAfter'
type MockBuffer_PasteAfter_Call struct {
	*mock.Call
}

// PasteAfter is a helper method to define mock.On call
//   - row int
//   - col int
//   - text string
//   - linewise bool
func (_e *MockBuffer_Expecter) PasteAfter(row interface{}, col interface{}, text interface{}, linewise interface{}) *MockBuffer_PasteAfter_Call {
	return &MockBuffer_PasteAfter_Call{Call: _e.mock.On("PasteAfter", row, col, text, linewise)}
}

func (_c *MockBuffer_PasteAfter_Call) Run(run func(row int, col int, text string, linewise bool)) *MockBuffer_PasteAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockBuffer_PasteAfter_Call) Return(newRow int, newCol int) *MockBuffer_PasteAfter_Call {
	_c.Call.Return(newRow, newCol)
	return _c
}

func (_c *MockBuffer_PasteAfter_Call) RunAndReturn(run func(int, int, string, bool) (int, int)) *MockBuffer_PasteAfter_Call {
	_c.Call.Return(run)
	return _c
}

// PasteBefore provides a mock function with given fields: row, col, text, linewise
func (_m *MockBuffer) PasteBefore(row int, col int, text string, linewise bool) (int, int) {
	ret := _m.Called(row, col, text, linewise)

	if len(ret) == 0 {
		panic("no return value specified for PasteBefore")
	}

	var r0 int
	var r1 int
	if rf, ok := ret.Get(0).(func(int, int, string, bool) (int, int)); ok {
		return rf(row, col, text, linewise)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, bool) int); ok {
		r0 = rf(row, col, text, linewise)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int, string, bool) int); ok {
		r1 = rf(row, col, text, linewise)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// MockBuffer_PasteBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasteBefore'
type MockBuffer_PasteBefore_Call struct {
	*mock.Call
}

// PasteBefore is a helper method to define mock.On call
//   - row int
//   - col int
//   - text string
//   - linewise bool
func (_e *MockBuffer_Expecter) PasteBefore(row interface{}, col interface{}, text interface{}, linewise interface{}) *MockBuffer_PasteBefore_Call {
	return &MockBuffer_PasteBefore_Call{Call: _e.mock.On("PasteBefore", row, col, text, linewise)}
}

func (_c *MockBuffer_PasteBefore_Call) Run(run func(row int, col int, text string, linewise bool)) *MockBuffer_PasteBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockBuffer_PasteBefore_Call) Return(newRow int, newCol int) *MockBuffer_PasteBefore_Call {
	_c.Call.Return(newRow, newCol)
	return _c
}

func (_c *MockBuffer_PasteBefore_Call) RunAndReturn(run func(int, int, string, bool) (int, int)) *MockBuffer_PasteBefore_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function with no fields
func (_m *MockBuffer) Path() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBuffer_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockBuffer_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Path() *MockBuffer_Path_Call {
	return &MockBuffer_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockBuffer_Path_Call) Run(run func()) *MockBuffer_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Path_Call) Return(_a0 string) *MockBuffer_Path_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_Path_Call) RunAndReturn(run func() string) *MockBuffer_Path_Call {
	_c.Call.Return(run)
	return _c
}

// Redo provides a mock function with no fields
func (_m *MockBuffer) Redo() (int, int, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Redo")
	}

	var r0 int
	var r1 int
	var r2 bool
	if rf, ok := ret.Get(0).(func() (int, int, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func() bool); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockBuffer_Redo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redo'
type MockBuffer_Redo_Call struct {
	*mock.Call
}

// Redo is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Redo() *MockBuffer_Redo_Call {
	return &MockBuffer_Redo_Call{Call: _e.mock.On("Redo")}
}

func (_c *MockBuffer_Redo_Call) Run(run func()) *MockBuffer_Redo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Redo_Call) Return(row int, col int, ok bool) *MockBuffer_Redo_Call {
	_c.Call.Return(row, col, ok)
	return _c
}

func (_c *MockBuffer_Redo_Call) RunAndReturn(run func() (int, int, bool)) *MockBuffer_Redo_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with no fields
func (_m *MockBuffer) Save() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBuffer_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockBuffer_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Save() *MockBuffer_Save_Call {
	return &MockBuffer_Save_Call{Call: _e.mock.On("Save")}
}

func (_c *MockBuffer_Save_Call) Run(run func()) *MockBuffer_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Save_Call) Return(_a0 error) *MockBuffer_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_Save_Call) RunAndReturn(run func() error) *MockBuffer_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SetCursorHint provides a mock function with given fields: row, col
func (_m *MockBuffer) SetCursorHint(row int, col int) {
	_m.Called(row, col)
}

// MockBuffer_SetCursorHint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCursorHint'
type MockBuffer_SetCursorHint_Call struct {
	*mock.Call
}

// SetCursorHint is a helper method to define mock.On call
//   - row int
//   - col int
func (_e *MockBuffer_Expecter) SetCursorHint(row interface{}, col interface{}) *MockBuffer_SetCursorHint_Call {
	return &MockBuffer_SetCursorHint_Call{Call: _e.mock.On("SetCursorHint", row, col)}
}

func (_c *MockBuffer_SetCursorHint_Call) Run(run func(row int, col int)) *MockBuffer_SetCursorHint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBuffer_SetCursorHint_Call) Return() *MockBuffer_SetCursorHint_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_SetCursorHint_Call) RunAndReturn(run func(int, int)) *MockBuffer_SetCursorHint_Call {
	_c.Run(run)
	return _c
}

// SetPath provides a mock function with given fields: path
func (_m *MockBuffer) SetPath(path string) {
	_m.Called(path)
}

// MockBuffer_SetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPath'
type MockBuffer_SetPath_Call struct {
	*mock.Call
}

// SetPath is a helper method to define mock.On call
//   - path string
func (_e *MockBuffer_Expecter) SetPath(path interface{}) *MockBuffer_SetPath_Call {
	return &MockBuffer_SetPath_Call{Call: _e.mock.On("SetPath", path)}
}

func (_c *MockBuffer_SetPath_Call) Run(run func(path string)) *MockBuffer_SetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBuffer_SetPath_Call) Return() *MockBuffer_SetPath_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBuffer_SetPath_Call) RunAndReturn(run func(string)) *MockBuffer_SetPath_Call {
	_c.Run(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockBuffer) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBuffer_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockBuffer_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) String() *MockBuffer_String_Call {
	return &MockBuffer_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockBuffer_String_Call) Run(run func()) *MockBuffer_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_String_Call) Return(_a0 string) *MockBuffer_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_String_Call) RunAndReturn(run func() string) *MockBuffer_String_Call {
	_c.Call.Return(run)
	return _c
}

// Undo provides a mock function with no fields
func (_m *MockBuffer) Undo() (int, int, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Undo")
	}

	var r0 int
	var r1 int
	var r2 bool
	if rf, ok := ret.Get(0).(func() (int, int, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func() bool); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockBuffer_Undo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Undo'
type MockBuffer_Undo_Call struct {
	*mock.Call
}

// Undo is a helper method to define mock.On call
func (_e *MockBuffer_Expecter) Undo() *MockBuffer_Undo_Call {
	return &MockBuffer_Undo_Call{Call: _e.mock.On("Undo")}
}

func (_c *MockBuffer_Undo_Call) Run(run func()) *MockBuffer_Undo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBuffer_Undo_Call) Return(row int, col int, ok bool) *MockBuffer_Undo_Call {
	_c.Call.Return(row, col, ok)
	return _c
}

func (_c *MockBuffer_Undo_Call) RunAndReturn(run func() (int, int, bool)) *MockBuffer_Undo_Call {
	_c.Call.Return(run)
	return _c
}

// YankLines provides a mock function with given fields: r1, r2
func (_m *MockBuffer) YankLines(r1 int, r2 int) string {
	ret := _m.Called(r1, r2)

	if len(ret) == 0 {
		panic("no return value specified for YankLines")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int, int) string); ok {
		r0 = rf(r1, r2)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBuffer_YankLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'YankLines'
type MockBuffer_YankLines_Call struct {
	*mock.Call
}

// YankLines is a helper method to define mock.On call
//   - r1 int
//   - r2 int
func (_e *MockBuffer_Expecter) YankLines(r1 interface{}, r2 interface{}) *MockBuffer_YankLines_Call {
	return &MockBuffer_YankLines_Call{Call: _e.mock.On("YankLines", r1, r2)}
}

func (_c *MockBuffer_YankLines_Call) Run(run func(r1 int, r2 int)) *MockBuffer_YankLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockBuffer_YankLines_Call) Return(_a0 string) *MockBuffer_YankLines_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_YankLines_Call) RunAndReturn(run func(int, int) string) *MockBuffer_YankLines_Call {
	_c.Call.Return(run)
	return _c
}

// YankRange provides a mock function with given fields: r1, c1, r2, c2
func (_m *MockBuffer) YankRange(r1 int, c1 int, r2 int, c2 int) string {
	ret := _m.Called(r1, c1, r2, c2)

	if len(ret) == 0 {
		panic("no return value specified for YankRange")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int, int, int, int) string); ok {
		r0 = rf(r1, c1, r2, c2)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBuffer_YankRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'YankRange'
type MockBuffer_YankRange_Call struct {
	*mock.Call
}

// YankRange is a helper method to define mock.On call
//   - r1 int
//   - c1 int
//   - r2 int
//   - c2 int
func (_e *MockBuffer_Expecter) YankRange(r1 interface{}, c1 interface{}, r2 interface{}, c2 interface{}) *MockBuffer_YankRange_Call {
	return &MockBuffer_YankRange_Call{Call: _e.mock.On("YankRange", r1, c1, r2, c2)}
}

func (_c *MockBuffer_YankRange_Call) Run(run func(r1 int, c1 int, r2 int, c2 int)) *MockBuffer_YankRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockBuffer_YankRange_Call) Return(_a0 string) *MockBuffer_YankRange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBuffer_YankRange_Call) RunAndReturn(run func(int, int, int, int) string) *MockBuffer_YankRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBuffer creates a new instance of MockBuffer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBuffer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBuffer {
	mock := &MockBuffer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
